// <auto-generated />
using CodeFirst.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirst.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240418074843_UpdateAgeColumnAndSeekData")]
    partial class UpdateAgeColumnAndSeekData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeFirst.Models.Khoa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("tenKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Khoas");

                    b.HasData(
                        new
                        {
                            id = 1,
                            tenKhoa = "Khoa công nghệ số"
                        },
                        new
                        {
                            id = 2,
                            tenKhoa = "Khoa điện - điện tử"
                        },
                        new
                        {
                            id = 3,
                            tenKhoa = "Khoa cơ khí"
                        },
                        new
                        {
                            id = 4,
                            tenKhoa = "Khoa xây dựng"
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Lop", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("khoaId")
                        .HasColumnType("int");

                    b.Property<string>("tenLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("khoaId");

                    b.ToTable("Lops");

                    b.HasData(
                        new
                        {
                            id = 1,
                            khoaId = 1,
                            tenLop = "21T1"
                        },
                        new
                        {
                            id = 2,
                            khoaId = 1,
                            tenLop = "21T2"
                        },
                        new
                        {
                            id = 3,
                            khoaId = 1,
                            tenLop = "21T3"
                        },
                        new
                        {
                            id = 4,
                            khoaId = 2,
                            tenLop = "21D1"
                        },
                        new
                        {
                            id = 5,
                            khoaId = 2,
                            tenLop = "21D2"
                        },
                        new
                        {
                            id = 6,
                            khoaId = 2,
                            tenLop = "21D3"
                        },
                        new
                        {
                            id = 7,
                            khoaId = 3,
                            tenLop = "21C1"
                        },
                        new
                        {
                            id = 8,
                            khoaId = 3,
                            tenLop = "21C2"
                        },
                        new
                        {
                            id = 9,
                            khoaId = 3,
                            tenLop = "21C3"
                        },
                        new
                        {
                            id = 10,
                            khoaId = 4,
                            tenLop = "21XD1"
                        },
                        new
                        {
                            id = 11,
                            khoaId = 4,
                            tenLop = "21XD1"
                        },
                        new
                        {
                            id = 12,
                            khoaId = 4,
                            tenLop = "21XD1"
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.SinhVien", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<int>("lopId")
                        .HasColumnType("int");

                    b.Property<string>("tenSinhVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("lopId");

                    b.ToTable("SinhViens");

                    b.HasData(
                        new
                        {
                            id = 1,
                            age = 20,
                            lopId = 3,
                            tenSinhVien = "Trần Công Quang Phú"
                        },
                        new
                        {
                            id = 2,
                            age = 21,
                            lopId = 1,
                            tenSinhVien = "Phạm Thanh Trúc"
                        },
                        new
                        {
                            id = 3,
                            age = 19,
                            lopId = 5,
                            tenSinhVien = "Lê Phước Đức"
                        },
                        new
                        {
                            id = 4,
                            age = 22,
                            lopId = 6,
                            tenSinhVien = "Trần Văn Lượng"
                        },
                        new
                        {
                            id = 5,
                            age = 19,
                            lopId = 2,
                            tenSinhVien = "Hồ Đăng Quốc Anh"
                        },
                        new
                        {
                            id = 6,
                            age = 18,
                            lopId = 3,
                            tenSinhVien = "Trương Văn Lâm"
                        },
                        new
                        {
                            id = 7,
                            age = 18,
                            lopId = 7,
                            tenSinhVien = "Phan Lê Văn Minh"
                        },
                        new
                        {
                            id = 8,
                            age = 19,
                            lopId = 12,
                            tenSinhVien = "Phạm Văn Bảo"
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Lop", b =>
                {
                    b.HasOne("CodeFirst.Models.Khoa", "khoa")
                        .WithMany()
                        .HasForeignKey("khoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("khoa");
                });

            modelBuilder.Entity("CodeFirst.Models.SinhVien", b =>
                {
                    b.HasOne("CodeFirst.Models.Lop", "lop")
                        .WithMany()
                        .HasForeignKey("lopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("lop");
                });
#pragma warning restore 612, 618
        }
    }
}
